### ISSUE TITLE
Kubedock and concurrency

### ISSUE THREAD

**Issue by rcgeorge23** [joyrex2001/kubedock#28]
Hi there,

I have a question about concurrency.

We are using kubedock as a standalone service running in kubernetes. I have managed to get things pretty stable, however some strange things happen when I try to kick off several builds (which talk to kubedock) at the same time (e.g. multiple copies of the same service being spun up etc). I have not really dug into this yet so I am unsure of the cause.

Can kubedock be used in this way? Or is it only intended to be used by one process at a time?

Thanks

**Comment by joyrex2001** [comment]
The short answer is no. 

This is because of the network aliases. A network alias is basically a hostname, which the containers can use to talk to each other. 

A good example is kafka+zookeeper. This configuration requires a hostname in the kafka container, pointing towards zookeeper. So, what is usually done in this case, is that zookeeper is given the network alias ‘zookeeper’ and in the kafka config this is hardcoded to zookeeper as well.

The k8s equivalent of this network alias, is a service. If you would run two of these zookeepers, with the network alias, a naming conflict exists. 

This can be workaround by with short-lived kubedock instances, which lock itself when started (the tekton sidecard example does this). Or, create a separate namespace per run.

A kubedock native implementation would be that kubedock would create namespaces per docker-network (making it unique again), but I am unsure if this added complexity is something that would be used a lot (as a kubedock run would create and delete namespaces as well).

My assumption is that you are using gitlab (or something similar), maybe some logic in front of kubedock is a more simple solution (either locking, pooling through some pre-defined namespaces, or create namespaces on the fly).

**Comment by rcgeorge23** [comment]
Hi Vincent - thanks for your reply.

Ok understood (I think), but if you're careful to configure your containers so that they assign themselves random network aliases, is there any reason why in principle kubedock running as a standalone service wouldn't be able to serve concurrent test processes that want to spin up pods in k8s?

I'm hoping that the taking the above precaution would enable us to avoid locking or the complexity of spinning up short lived namespaces.

RE: kafka specifically, if you're just running a single broker with embedded zookeeper, it looks like zookeeper starts up as a new process within the kafka container and the broker process talks to it on `localhost:2181`, so as far as I can see I don't think there would be a service name clash there.

**Comment by rcgeorge23** [comment]
Going to close this, as I think I've got to the bottom of the weird behaviour I was seeing.

Kubedock seems fine to run concurrently if you're careful with service hostnames.
