### ISSUE TITLE
Lease hangs indefinitely when Kubedock quits unexpectedly

### ISSUE THREAD

**Issue by renjfk** [joyrex2001/kubedock#80]
When Kubedock quits unexpectedly e.g. the Kubedock's containing pod gets killed or crashes, Kubedock is not able to release the lease as well as remaining workloads/pods. This is quite expected and possibly can be handled by a scheduled job for cleaning.

But I'm wondering if we can handle this directly on Kubedock's side such as if a lease hasn't been renewed for some defined time; it will forcefully acquire it and then clean all leftover workloads.

How does it sound; something would fit Kubedock's definition or outside of the scope?

**Comment by renjfk** [comment]
That doesn't seem to be the case on our pipeline since every now and then I find bunch of namespaces with leases unobtainable due to they are attached somewhere. 🤷

I'll investigate this further and try to reproduce consistently but in any case; even if it acquires lease, how about cleaning up stale workloads?

**Comment by joyrex2001** [comment]
I can't reproduce the waiting part, however it doesn't log acquiring the lock using the default loglevel. If you increase the loglevel to 3 (-v 3), it will also log when it acquired the lease.

I don't think it's a good idea to take a bit of the responsibility in my code, and remove leases myself (instead of the leader election implementation in the kubernetes client-go library). Removing the leases can only safely done if you are actually owning the lock at that point in time (having the lock), which complicates thing by a lot.

**Comment by renjfk** [comment]
> I don't think it's a good idea to take a bit of the responsibility in my code, and remove leases myself

I'm not talking about removing leases but the leftover pods created by Kubedock from earler sessions. 🤔

**Comment by joyrex2001** [comment]
If you start with `--prune-start` (or `-P`), it will delete older kubedock resources before starting, is this what you are looking for?

**Comment by renjfk** [comment]
Aha, guess I have missed the end of documentation, thanks! 🤦 There also seems to be automatic reaping but for some reason this is not working in our pipeline.

But either way the way I understand; Kubedock is capable of recovering itself from such disaster scenarios out of the box.
